### ISSUE TITLE
Register order as placed (ok), before payment is confirmed.

### ISSUE THREAD

**Issue by Freakshows** [coingate/opencart-plugin#1]
The module itself is working ok, but there are a problem; it register the order as placed and OK, before payment is confirmed. This is not a good situation, so a fix for this would be more than welcome.

**Comment by minvs1** [comment]
Could you please elaborate on what you mean? Can you give an example with specific details?

**Comment by Freakshows** [comment]
What i mean is that opencart generate (place) the order before payment with bitcoin is complete and successfull.
All my other payment modules do not generate the order before payment is successful.

**Comment by minvs1** [comment]
When an order is placed, it is generated with a default status (usually "pending"). When an order is paid, its status is changed to "completed" (or whichever status you chose to set your orders to after they are paid). Is this not what happens when using CoinGate plugin?

**Comment by Freakshows** [comment]
The order get the status _pending_ yes, just as all normal incomming placed orders.

**Comment by Freakshows** [comment]
i have not tested with actualy paying an order with bitcoins, but i find it strange in any case that the order is generated at all without a successfull payment, or?

**Comment by minvs1** [comment]
As you said yourself, this happens for all normal incoming placed orders. This is normal, expected behavior. If an order was not generated until being successfully paid for, then the merchant and their client could not communicate about an order, if the payment attempt was made, but not successfully completed.

**Comment by Freakshows** [comment]
well, the big difference is that i don't get any orders at all before a payment is successfull, when using all my other payment gateways

**Comment by minvs1** [comment]
Creating an order before a successful payment is useful for these reasons:
1. Keeping statistics about how many times your customers failed to pay successfully and for what reasons (order expired, payment failed, payment was not made, etc.);
2. Making it easier for you (the merchant) and your customers to communicate about an order, if a payment attempt was made, but not successfully completed.

This is normal, expected behavior for CoinGate plugin, and there are no plans to change it.

**Comment by Freakshows** [comment]
I do accept that there are no plans to change this, that is ok, but for your arguments, well, they are just not valid and here is why:
1. there are full statistics in opencart already for unfinnished orderes, every time you click on confirm order in opencart a order number is generated, and the order can be found in admin panel/orders then filter on "Missing orders", then you will see all attemts made and all info on what have happen on the checkout page.
2. to discuss an order that is not valid with a customer, well that is just a big wast of time, because there really is nothing to discuss. normaly the customer will contact you thru mail or form if there is anything to discuss.
